name: Some

on: push

env: 
  COMMIT_HASH: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Terraform Cli
        uses: hashicorp/setup-terraform@v3

      - id:   install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2          # default
          verbose: false      # default
          arch: amd64

      - name: Clone base repo
        run:  git clone https://github.com/tereza-arta/terraform-code.git

      - name: Checkout
        uses: actions/checkout@v3

      - run : terraform init
      - run : terraform plan
      - run : terraform apply -var="instance_name=${{ env.COMMIT_HASH }}"
